---
argument_specs:
  # roles/configure_meraki_mr/main.yml entry point
  main:
    short_description: Role to configure Meraki MR Access Points
    author: Nick Thompson <github/@nsthompson>
    options:
      dashboard_base_url:
        type: str
        required: true
        description: Meraki Dashboard Base URL
      auth_key:
        type: str
        required: true
        description: Meraki API Auth Key
      meraki_mr_configuration:
        type: dict
        required: true
        options:
          access_points:
            type: list
            required: true
            elements: dict
            description: Access Point Configuration
            options:
              name:
                type: str
                required: true
                description: Name of MX Appliance
              organization:
                type: str
                required: true
                description: Meraki Organization
              network:
                type: str
                required: true
                description: Meraki Network Name
              rf_profile_name:
                type: str
                required: false
                description: RF Profile Name
              general_settings:
                type: dict
                required: false
                description: General MR Settings
                options:
                  ipv6_bridge_enabled:
                    type: bool
                    required: false
                    description: Enable Wireless IPv6 Bridging
                  led_lights_on:
                    type: bool
                    required: false
                    description: Enable LED lights on Access Points
                  location_analytics_enabled:
                    type: bool
                    required: false
                    description: Enable Location Analytics
                  meshing_enabled:
                    type: bool
                    required: false
                    description: Enable Wireless Mesh
                  upgrade_strategy:
                    type: str
                    required: false
                    description: Firmware Upgrade Strategy
                    choices:
                      - minimize_upgrade_time
                      - minimize_client_downtime
              bluetooth_settings:
                type: dict
                required: false
                description: MR Bluetooth Settings
                options:
                  scanning_enabled:
                    type: bool
                    required: false
                    description: BLE Scanning Enabled
                  beaconing_enabled:
                    type: bool
                    required: false
                    description: Enable BLE Beaconing
                  uuid:
                    type: str
                    required: false
                    description: Bluetooth UUID
                  major_minor_assignment_mode:
                    type: str
                    required: false
                    description: The way major and minor number should be assigned
                    choices:
                      - Unique
                      - Non-unique
                  major:
                    type: int
                    required: false
                    description: Major number in beacon identifier - only valid in non-unique mode
                  minor:
                    type: int
                    required: false
                    description: Minor number in beacon identifier - only valid in non-unique mode
              rf_profiles:
                type: list
                required: false
                elements: dict
                description: RF Profile Configuration
                options:
                  name:
                    type: str
                    required: false
                    description: Name of RF Profile
                  state:
                    type: str
                    required: false
                    description: State of Profile
                    choices:
                      - present
                      - absent
                  band_selection_type:
                    type: str
                    required: false
                    description: Band Selection assigned per AP or SSID
                    choices:
                      - ap
                      - ssid
                  client_balancing_enabled:
                    type: bool
                    required: false
                    description: Steer Client to best available AP
                  ap_band_settings:
                    type: dict
                    required: false
                    description: Settings if band_selection_type is 'ap'
                    options:
                      mode:
                        type: str
                        required: false
                        description: RF band the AP will support
                        choices:
                          - 2.4ghz
                          - 5ghz
                          - dual
                      band_steering_enabled:
                        type: bool
                        required: false
                        description: Steers client to most open band
                  five_ghz_settings:
                    type: dict
                    required: false
                    description: 5Ghz band settings
                    options:
                      max_power:
                        type: int
                        required: false
                        description: Max power in dBm of 5Ghz band
                        choices:
                          - 8
                          - 9
                          - 10
                          - 11
                          - 12
                          - 13
                          - 14
                          - 15
                          - 16
                          - 17
                          - 18
                          - 19
                          - 20
                          - 21
                          - 22
                          - 23
                          - 24
                          - 25
                          - 26
                          - 27
                          - 28
                          - 29
                          - 30
                      min_bitrate:
                        type: int
                        required: false
                        description: Minimum bitrate of 5Ghz band
                        choices:
                          - 6
                          - 9
                          - 12
                          - 18
                          - 24
                          - 36
                          - 48
                          - 54
                      min_power:
                        type: int
                        required: false
                        description: Minimum power in dBm of 5Ghz band
                        choices:
                          - 8
                          - 9
                          - 10
                          - 11
                          - 12
                          - 13
                          - 14
                          - 15
                          - 16
                          - 17
                          - 18
                          - 19
                          - 20
                          - 21
                          - 22
                          - 23
                          - 24
                          - 25
                          - 26
                          - 27
                          - 28
                          - 29
                          - 30
                      rxsop:
                        type: int
                        required: false
                        description: controls the sensitivity of the radio - range -65 to -95
                      channel_width:
                        type: str
                        required: false
                        description: Channel width for 5Ghz band
                        choices:
                          - auto
                          - "20"
                          - "40"
                          - "80"
                      valid_auto_channels:
                        type: list
                        elements: int
                        required: false
                        description: Valid auto channels for 5ghz band
                        choices:
                          - 36
                          - 40
                          - 44
                          - 48
                          - 52
                          - 56
                          - 60
                          - 64
                          - 100
                          - 104
                          - 108
                          - 112
                          - 116
                          - 120
                          - 124
                          - 128
                          - 132
                          - 136
                          - 140
                          - 144
                          - 149
                          - 153
                          - 157
                          - 161
                          - 165
                  two_four_ghz_settings:
                    type: dict
                    required: false
                    description: 2.4Ghz band settings
                    options:
                      max_power:
                        type: int
                        required: false
                        description: Max power in dBm of 2.4Ghz band
                        choices:
                          - 5
                          - 6
                          - 7
                          - 8
                          - 9
                          - 10
                          - 11
                          - 12
                          - 13
                          - 14
                          - 15
                          - 16
                          - 17
                          - 18
                          - 19
                          - 20
                          - 21
                          - 22
                          - 23
                          - 24
                          - 25
                          - 26
                          - 27
                          - 28
                          - 29
                          - 30
                      min_bitrate:
                        type: int
                        required: false
                        description: Minimum bitrate of 2.4Ghz band
                        choices:
                          - 1.0
                          - 2.0
                          - 5.5
                          - 6.0
                          - 9.0
                          - 11.0
                          - 12.0
                          - 18.0
                          - 24.0
                          - 36.0
                          - 48.0
                          - 54.0
                      min_power:
                        type: int
                        required: false
                        description: Minimum power in dBm of 2.4Ghz band
                        choices:
                          - 5
                          - 6
                          - 7
                          - 8
                          - 9
                          - 10
                          - 11
                          - 12
                          - 13
                          - 14
                          - 15
                          - 16
                          - 17
                          - 18
                          - 19
                          - 20
                          - 21
                          - 22
                          - 23
                          - 24
                          - 25
                          - 26
                          - 27
                          - 28
                          - 29
                          - 30
                      rxsop:
                        type: int
                        required: false
                        description: controls the sensitivity of the radio - range -65 to -95
                      ax_enabled:
                        type: bool
                        required: false
                        description: Enable AX radio on 2.4Ghz band
                      valid_auto_channels:
                        type: list
                        elements: int
                        required: false
                        description: Valid Auto Channels for 2.4
                        choices:
                          - 1
                          - 6
                          - 11
              ssids:
                type: list
                elements: dict
                required: false
                description: SSID Configurations
                options:
                  name:
                    type: str
                    required: false
                    description: Name of SSID
                  state:
                    type: str
                    required: false
                    description: SSID state
                    choices:
                      - present
                      - absent
                  enabled:
                    type: bool
                    required: false
                    description: Enable SSID
                  visible:
                    type: bool
                    required: false
                    description: Broadcast SSID
                  available_on_all_aps:
                    type: bool
                    required: false
                    description: Enable SSID on all APs
                  authentication:
                    type: dict
                    required: false
                    description: Authentication Configuration
                    options:
                      auth_mode:
                        type: str
                        required: false
                        description: Auth mode of network
                        choices:
                          - open
                          - open-enhanced
                          - psk
                          - open-with-radius
                          - open-with-nac
                          - 8021x-meraki
                          - 8021x-radius
                          - 8021x-google
                          - 8021x-localradius
                          - ipsk-with-radius
                          - ipsk-without-radius
                      psk:
                        type: str
                        required: false
                        description: Pre-Shared-Key
                      encryption_mode:
                        type: str
                        required: false
                        description: Encryption Mode of Network
                        choices:
                          - wpa
                          - eap
                          - wpa-eap
                      wpa_encryption_mode:
                        type: str
                        required: false
                        description: WPA Encryption Mode
                        choices:
                          - WPA1 only
                          - WPA1 and WPA2
                          - WPA2 only
                          - WPA3 Transition Mode
                          - WPA3 only
                          - WPA3 192-bit Security
                  vlan:
                    type: dict
                    required: false
                    description: VLAN Configuration
                    options:
                      use_vlan_tagging:
                        type: bool
                        required: false
                        description: Use VLAN Tagging
                      default_vlan_id:
                        type: str
                        required: false
                        description: Default VLAN ID
                  ip_assignment_mode:
                    type: str
                    required: false
                    description: IP Assignment mode
                    choices:
                      - NAT mode
                      - Bridge mode
                      - Layer 3 roaming
                      - Layer 3 roaming with a concentrator
                      - VPN
                  lan_isolation_enabled:
                    type: bool
                    required: false
                    description: Layer 2 LAN Isolation
                  splash_page:
                    type: str
                    required: false
                    description: Enable Splash Page
                    choices:
                      - None
                      - Click-through splash page
                      - Billing
                      - Password-protected with Meraki RADIUS
                      - Password-protected with custom RADIUS
                      - Password-protected with Active Directory
                      - Password-protected with LDAP
                      - SMS authentication
                      - Systems Manager Sentry
                      - Facebook Wi-Fi
                      - Google OAuth
                      - Sponsored guest
                      - Cisco ISE
