---
- name: Query for existing Camera Wireless Profiles
  cisco.meraki.networks_camera_wireless_profiles_info:
    meraki_api_key: "{{ auth_key }}"
    networkId: "{{ network_id }}"
  register: profile_result
  when: meraki_mv_configuration.camera_profiles.wireless is defined

- name: Add discovered profiles to dict
  ansible.builtin.set_fact:
    wireless_profile_ids: >-
      {{ wireless_profile_ids | default({}) | combine(
        {
          result.name: {
            "id": result.id,
          }
        }
      ) }}
  loop: "{{ profile_result.meraki_response }}"
  loop_control:
    loop_var: result
  when: profile_result is defined

- name: Create Camera Wireless Profiles for Network {{ meraki_mv_configuration.network.name }}
  cisco.meraki.networks_camera_wireless_profiles:
    meraki_api_key: "{{ auth_key }}"
    state: "{{ profile.state }}"
    name: "{{ profile.name }}"
    networkId: "{{ network_id }}"
    ssid: "{{ profile.ssid }}"
    identity: "{{ profile.identity | default(omit) }}"
  loop: "{{ meraki_mv_configuration.camera_profiles.wireless }}"
  loop_control:
    loop_var: profile
  when: wireless_profile_ids[profile.name] is not defined and profile.state == "present"

- name: Update Camera Wireless Profiles for Network {{ meraki_mv_configuration.network.name }}
  cisco.meraki.networks_camera_wireless_profiles:
    meraki_api_key: "{{ auth_key }}"
    state: "{{ profile.state }}"
    name: "{{ profile.name }}"
    networkId: "{{ network_id }}"
    ssid: "{{ profile.ssid }}"
    identity: "{{ profile.identity | default(omit) }}"
    wirelessProfileId: "{{ wireless_profile_ids[profile.name].id }}"
  loop: "{{ meraki_mv_configuration.camera_profiles.wireless }}"
  loop_control:
    loop_var: profile
  when: wireless_profile_ids[profile.name] is defined and profile.state == "present"

- name: Delete Camera Wireless Profiles for Network {{ meraki_mv_configuration.network.name }}
  cisco.meraki.networks_camera_wireless_profiles:
    meraki_api_key: "{{ auth_key }}"
    state: "{{ profile.state }}"
    networkId: "{{ network_id }}"
    wirelessProfileId: "{{ wireless_profile_ids[profile.name].id }}"
  loop: "{{ meraki_mv_configuration.camera_profiles.wireless }}"
  loop_control:
    loop_var: profile
  when: wireless_profile_ids[profile.name] is defined and profile.state == "absent"
