---
- name: Query for existing Camera Quality and Retention Profiles
  cisco.meraki.networks_camera_quality_retention_profiles_info:
    meraki_api_key: "{{ auth_key }}"
    networkId: "{{ network_id }}"
  register: profile_result
  when: meraki_mv_configuration.camera_profiles.quality_and_retention is defined

- name: Add discovered profiles to dict
  ansible.builtin.set_fact:
    quality_profile_ids: >-
      {{ quality_profile_ids | default({}) | combine(
        {
          result.name: {
            "id": result.id,
          }
        }
      ) }}
  loop: "{{ profile_result.meraki_response }}"
  loop_control:
    loop_var: result
  when: profile_result is defined

- name: Create Camera Quality and Retention Profiles for Network {{ meraki_mv_configuration.network.name }}
  cisco.meraki.networks_camera_quality_retention_profiles:
    meraki_api_key: "{{ auth_key }}"
    state: "{{ profile.state }}"
    name: "{{ profile.name }}"
    networkId: "{{ network_id }}"
    audioRecordingEnabled: "{{ profile.audioRecordingEnabled | default(omit) }}"
    cloudArchiveEnabled: "{{ profile.cloudArchiveEnabled | default(omit) }}"
    maxRetentionDays: "{{ profile.maxRetentionDays | default(omit) }}"
    motionBasedRetentionEnabled: "{{ profile.motionBasedRetentionEnabled | default(omit) }}"
    motionDetectorVersion: "{{ profile.motionDetectorVersion | default(omit) }}"
    restrictedBandwidthModeEnabled: "{{ profile.restrictedBandwidthModeEnabled | default(omit) }}"
    scheduleId: "{{ profile.scheduleId | default(omit) }}"
    videoSettings: "{{ profile.videoSettings | default(omit) }}"
  loop: "{{ meraki_mv_configuration.camera_profiles.quality_and_retention }}"
  loop_control:
    loop_var: profile
  when: quality_profile_ids[profile.name] is not defined and profile.state == "present"

- name: Update Camera Quality and Retention Profiles for Network {{ meraki_mv_configuration.network.name }}
  cisco.meraki.networks_camera_quality_retention_profiles:
    meraki_api_key: "{{ auth_key }}"
    state: "{{ profile.state }}"
    name: "{{ profile.name }}"
    networkId: "{{ network_id }}"
    qualityRetentionProfileId: "{{ quality_profile_ids[profile.name].id }}"
    audioRecordingEnabled: "{{ profile.audioRecordingEnabled | default(omit) }}"
    cloudArchiveEnabled: "{{ profile.cloudArchiveEnabled | default(omit) }}"
    maxRetentionDays: "{{ profile.maxRetentionDays | default(omit) }}"
    motionBasedRetentionEnabled: "{{ profile.motionBasedRetentionEnabled | default(omit) }}"
    motionDetectorVersion: "{{ profile.motionDetectorVersion | default(omit) }}"
    restrictedBandwidthModeEnabled: "{{ profile.restrictedBandwidthModeEnabled | default(omit) }}"
    scheduleId: "{{ profile.scheduleId | default(omit) }}"
    videoSettings: "{{ profile.videoSettings | default(omit) }}"
  loop: "{{ meraki_mv_configuration.camera_profiles.quality_and_retention }}"
  loop_control:
    loop_var: profile
  when: quality_profile_ids[profile.name] is defined and profile.state == "present"

- name: Update Camera Quality and Retention Profiles for Network {{ meraki_mv_configuration.network.name }}
  cisco.meraki.networks_camera_quality_retention_profiles:
    meraki_api_key: "{{ auth_key }}"
    state: "{{ profile.state }}"
    networkId: "{{ network_id }}"
    qualityRetentionProfileId: "{{ quality_profile_ids[profile.name].id }}"
  loop: "{{ meraki_mv_configuration.camera_profiles.quality_and_retention }}"
  loop_control:
    loop_var: profile
  when: quality_profile_ids[profile.name] is defined and profile.state == "absent"
