---
#
# Ansible Role to Configure Meraki MV Cameras
#
# Copyright (C) 2023 World Wide Technology
# All Rights Reserved
#
# Written by: Nick Thompson (github/@nsthompson)
#

- name: Look Up Meraki MV Network ID
  ansible.builtin.set_fact:
    network_id: "{{ lookup('wwt.meraki.fetch',
      'network_id',
      org_name=meraki_mv_configuration.network.organization,
      meraki_api_key=auth_key,
      network_name=meraki_mv_configuration.network.name) }}"

- name: Failure - Network DOES NOT exist
  ansible.builtin.fail:
    msg: Meraki Network is not provisioned
  when: network_id is not defined

- name: Configure Camera Wireless Profiles
  ansible.builtin.include_tasks: configure_wireless_profiles.yml

- name: Configure Camera Quality and Retention Profiles
  ansible.builtin.include_tasks: configure_quality_profiles.yml

- name: Configure Camera Settings
  ansible.builtin.include_tasks: configure_camera_settings.yml
  loop: "{{ meraki_mv_configuration.cameras }}"
  loop_control:
    loop_var: camera
