---
#
# Ansible Role to Configure Meraki MT Sensors
#
# Copyright (C) 2023 World Wide Technology
# All Rights Reserved
#
# Written by: Nick Thompson (github/@nsthompson)
#
- name: Look Up Meraki MT Sensor Network ID
  ansible.builtin.set_fact:
    network_id: "{{ lookup('wwt.meraki.fetch',
      'network_id',
      org_name=meraki_mt_configuration.network.organization,
      meraki_api_key=auth_key,
      network_name=meraki_mt_configuration.network.name) }}"

- name: Failure - Network DOES NOT exist
  ansible.builtin.fail:
    msg: Meraki Network is not provisioned
  when: network_id is not defined

- name: Configure MQTT
  ansible.builtin.include_tasks: configure_mqtt.yml

#
# Sensor Automation API Endpoint Is not published yet
#
# - name: Configure Sensor Automations
#   ansible.builtin.include_tasks: configure_sensor_automations.yml
#   vars:
#     network_id: "{{ network_ids[config.network]['network_id'] }}"
#   loop: "{{ meraki_mt_configuration }}"
#   loop_control:
#     loop_var: config
