---
- name: Look for existing network devices
  ansible.builtin.set_fact:
    device_serials: "{{ query('wwt.meraki.fetch', 'network_devices', network_name=network.name, org_name=network.organization, meraki_api_key=auth_key) }}"

- name: Remove Devices
  cisco.meraki.networks_devices_remove:
    meraki_api_key: "{{ auth_key }}"
    networkId: "{{ query('wwt.meraki.fetch', 'network_id', org_name=network.organization, meraki_api_key=auth_key, network_name=network.name) }}"
    serial: "{{ device }}"
  loop: "{{ device_serials }}"
  loop_control:
    loop_var: device
  when: device_serials is defined

- name: Configure Meraki Network
  cisco.meraki.networks:
    meraki_api_key: "{{ auth_key }}"
    state: "{{ network.state }}"
    networkId: "{{ query('wwt.meraki.fetch', 'network_id', org_name=network.organization, meraki_api_key=auth_key, network_name=network.name) }}"
  when: network.state == "absent"