---
- name: Register Meraki Device by Device Serial Number
  ansible.builtin.uri:
    url: "{{ dashboard_base_url }}/organizations/{{ org_id }}/claim"
    method: POST
    status_code: 200
    body: |
      {
        "serials": {{ serial_numbers }}
      }
    body_format: json
    headers:
      Content-Type: application/json
      X-Cisco-Meraki-API-Key: "{{ auth_key }}"
