---
- name: Register Meraki Device by License Keys
  ansible.builtin.uri:
    url: "{{ dashboard_base_url }}/organizations/{{ org_id }}/claim"
    method: POST
    status_code: 200
    body: |
      {
        "licenses": {{ lookup('template', 'templates/license_keys.j2') }}
      }
    body_format: json
    headers:
      Content-Type: application/json
      X-Cisco-Meraki-API-Key: "{{ auth_key }}"
