---
argument_specs:
  # roles/configure_meraki_mt/main.yml entry point
  main:
    short_description: Role to configure Meraki MT Sensors
    author: Nick Thompson <github/@nsthompson>
    options:
      dashboard_base_url:
        type: str
        required: true
        description: Meraki Dashboard Base URL
      auth_key:
        type: str
        required: true
        description: Meraki API Auth Key
      meraki_mt_configuration:
        type: dict
        required: true
        options:
          network:
            type: dict
            required: true
            description: Network Wide Settings for MX
            options:
              organization:
                type: str
                required: true
                description: Meraki Organization
              name:
                type: str
                required: true
                description: Meraki Network Name
          sensors:
            type: list
            required: true
            elements: dict
            description: Sensor Configuration
            options:
              name:
                type: str
                required: true
                description: Name of MT Sensor
              state:
                type: str
                description: Sensor State
                choices:
                  - present
                  - absent
          mqtt_brokers:
            type: list
            elements: dict
            required: false
            description: MQTT Broker Configuration
            options:
              name:
                type: str
                required: false
                description: MQTT Broker Name
              state:
                type: str
                required: false
                description: MQTT Broker State
                choices:
                  - present
                  - absent
              enabled:
                type: bool
                required: false
                description: Enable Broker - Only ONE broker can be active at a time
              host:
                type: str
                required: false
                description: MQTT host
              port:
                type: int
                required: false
                description: MQTT Server Port
              authentication:
                type: dict
                required: false
                options:
                  username:
                    type: str
                    required: false
                    description: MQTT Username
                  password:
                    type: str
                    required: false
                    description: MQTT Password
              security:
                type: dict
                required: false
                options:
                  mode:
                    type: str
                    required: false
                    description: Security Mode
                    choices:
                      - none
                      - tls
                  certFile:
                    type: str
                    required: false
                    description: CA Certificate File Path
                  verifyHostnames:
                    type: bool
                    required: false
                    description: Verify Hostnames
          automations:
            type: list
            elements: dict
            required: false
            description: MT Sensor Automations
            options:
              name:
                type: str
                required: false
                description: Automation Name
              enabled:
                type: bool
                required: false
                description: Automation Enabled
              icon:
                type: str
                required: false
                description: Automation Icon
                choices:
                  - rocket
                  - alarm
                  - atom
                  - barcode
                  - briefcase
                  - key
                  - flask
                  - sun
                  - chalkboard
                  - trophy
                  - traffic
                  - target
                  - chat
                  - shield
                  - trend
                  - warning
              conditions:
                type: list
                elements: dict
                required: false
                description: Automation Conditions
                options:
                  metric:
                    type: str
                    required: false
                    description: Metric Type
                    choices:
                      - button
                  button:
                    type: dict
                    required: false
                    description: Button Settings
                    options:
                      press_type:
                        type: str
                        required: false
                        description: Button Press Duration
                        choices:
                          - short
                          - long
                  serials:
                    type: list
                    elements: str
                    required: false
                    description: Sensor Serial Numbers
              targets:
                type: list
                elements: dict
                required: false
                description: Automation Targets
                options:
                  target:
                    type: str
                    required: false
                    description: Target Type
                    choices:
                      - notification
                      - snapshot
                      - ssid
                      - webhook
                  notification:
                    type: dict
                    required: false
                    description: Email or SMS Notification
                    options:
                      recipient:
                        type: str
                        required: false
                        description: Email Address or Phone Number
                      message:
                        type: str
                        required: false
                        description: Message - 255 Character Max
                      notification_type:
                        type: str
                        required: false
                        description: Notification Type
                        choices:
                          - email
                          - phone
                  snapshot:
                    type: dict
                    required: false
                    description: Camera Snapshot
                    options:
                      recipient:
                        type: str
                        required: false
                        description: Email Address or Phone Number
                      camera:
                        type: str
                        required: false
                        description: Camera Serial Number
                      notification_type:
                        type: str
                        required: false
                        description: Notification Type
                        choices:
                          - email
                          - phone
                  webhook:
                    type: dict
                    required: false
                    description: Webhook Alert
                    options:
                      id:
                        type: str
                        required: false
                        description: Meraki Webhook ID
                      message:
                        type: str
                        required: false
                        description: Webhook Message - 255 Character Max
                  ssid:
                    type: dict
                    required: false
                    description: Toggle SSID
                    options:
                      id:
                        type: str
                        required: false
                        description: Meraki SSID ID
                      action:
                        type: str
                        required: false
                        description: SSID Toggle Action
                        choices:
                          - disable
                          - enable
                          - toggle
          schedule:
            type: str
            required: false
            description: Sensor Schedule
