---
- name: Configure Meraki MX L3 Firewall for {{ appliance.name }}
  cisco.meraki.networks_appliance_firewall_l3_firewall_rules:
    meraki_api_key: "{{ auth_key }}"
    networkId: "{{ network_id }}"
    state: present
    rules: "{{ appliance.threat_protection.firewall.l3_rules }}"
