---
- name: Configure Meraki MX Deployment Settings
  cisco.meraki.networks_appliance_settings:
    meraki_api_key: "{{ auth_key }}"
    networkId: "{{ network_id }}"
    state: present
    clientTrackingMethod: "{{ appliance.deployment_settings.client_tracking }}"
    deploymentMode: "{{ appliance.deployment_settings.deployment_mode }}"
    dynamicDns:
      prefix: "{{ appliance.deployment_settings.dynamic_dns.prefix }}"
      enabled: "{{ appliance.deployment_settings.dynamic_dns.enabled }}"
