---
- name: Configure Meraki MX L7 Firewall for {{ appliance.name }}
  cisco.meraki.networks_appliance_firewall_l7_firewall_rules:
    meraki_api_key: "{{ auth_key }}"
    networkId: "{{ network_id }}"
    state: present
    rules: "{{ appliance.threat_protection.firewall.l7_rules }}"
