---
- name: Query Device Serial Number for {{ appliance.name }}
  ansible.builtin.set_fact:
    device_serial: "{{ lookup('wwt.meraki.fetch', 'network_devices', org_name=meraki_mx_configuration.network.organization, meraki_api_key=auth_key, network_name=meraki_mx_configuration.network.name, device_name=appliance.name) }}"

- name: Configure Meraki MX WAN Uplinks
  block:
    - name: Configure MX WAN Uplinks for {{ appliance.name }}
      ansible.builtin.uri:
        url: "{{ dashboard_base_url }}/devices/{{ device_serial }}/appliance/uplinks/settings"
        method: PUT
        status_code: 200
        headers:
          Content-Type: application/json
          X-Cisco-Meraki-API-Key: "{{ auth_key }}"
        body_format: json
        body: "{{ lookup('template', 'templates/wan_uplinks.j2') }}"
      changed_when: api_result.status == 200
      until: api_result.status != 429
      delay: 5
      retries: 3
      register: api_result
  rescue:
    - name: Something went wrong...
      ansible.builtin.debug:
        msg: "ERROR: {{ api_result }}"
