---
- name: Configure Meraki MX Advanced Malware Protection Settings
  cisco.meraki.networks_appliance_security_malware:
    meraki_api_key: "{{ auth_key }}"
    networkId: "{{ network_id }}"
    mode: "{{ appliance.threat_protection.malware.mode }}"
    allowedUrls: "{{ appliance.threat_protection.malware.allowed_urls }}"
    allowedFiles: "{{ appliance.threat_protection.malware.allowed_files | default(omit) }}"

- name: Configure Meraki MX Intrusion Detection and Prevention Settings for {{ appliance.name }}
  cisco.meraki.networks_appliance_security_intrusion:
    meraki_api_key: "{{ auth_key }}"
    networkId: "{{ network_id }}"
    state: present
    mode: "{{ appliance.threat_protection.intrusion.mode }}"
    protectedNetworks: "{{ appliance.threat_protection.intrusion.protected_networks | default(omit) }}"
    idsRulesets: "{{ appliance.threat_protection.intrusion.rulesets }}"
