---
- name: "Configure Meraki MX L3 Firewall for {{ appliance.name }}"
  cisco.meraki.meraki_mx_l3_firewall:
    auth_key: "{{ auth_key }}"
    org_name: "{{ appliance.organization }}"
    net_name: "{{ appliance.network }}"
    state: present
    rules: "{{ appliance.threat_protection.firewall.l3_rules }}"
