---
- name: Configure Meraki MX Ports for {{ appliance.name }}
  cisco.meraki.networks_appliance_ports:
    meraki_api_key: "{{ auth_key }}"
    networkId: "{{ network_id }}"
    portId: "{{ port.id }}"
    enabled: "{{ port.enabled }}"
    dropUntaggedTraffic: "{{ port.drop_untagged_traffic | default(omit) }}"
    type: "{{ port.type | default(omit) }}"
    vlan: "{{ port.vlan | default(omit) }}"
    allowedVlans: "{{ port.allowed_vlans | default(omit) }}"
    accessPolicy: "{{ port.access_policy | default(omit) }}"
  loop: "{{ appliance.ports }}"
  loop_control:
    loop_var: port
