---
#
# Ansible Role to Configure Meraki MX Appliances
#
# Copyright (C) 2023 World Wide Technology
# All Rights Reserved
#
# Written by: Nick Thompson (github/@nsthompson)
#
- name: Look Up Meraki MX Appliance Network ID
  ansible.builtin.set_fact:
    network_id: "{{ lookup('wwt.meraki.fetch', 'network_id', org_name=meraki_mx_configuration.network.organization, meraki_api_key=auth_key, network_name=meraki_mx_configuration.network.name) }}"

- name: Failure - Network DOES NOT exist
  ansible.builtin.fail:
    msg: Meraki Network is not provisioned
  when: network_id is not defined

- name: Configure Meraki MX Deployment Settings
  ansible.builtin.include_tasks: configure_deployment.yml
  loop: "{{ meraki_mx_configuration.appliances }}"
  loop_control:
    loop_var: appliance

- name: Configure Meraki MX WAN Uplinks
  ansible.builtin.include_tasks: configure_wan_uplinks.yml
  loop: "{{ meraki_mx_configuration.appliances }}"
  loop_control:
    loop_var: appliance

- name: Configure Meraki MX Network VLAN Settings
  cisco.meraki.networks_appliance_vlans_settings:
    meraki_api_key: "{{ auth_key }}"
    networkId: "{{ network_id }}"
    state: present
    vlansEnabled: "{{ meraki_mx_configuration.network.lan_settings.enable_vlans }}"

- name: Configure Meraki MX VLANs
  ansible.builtin.include_tasks: configure_vlans.yml
  loop: "{{ meraki_mx_configuration.appliances }}"
  loop_control:
    loop_var: appliance

- name: Configure Meraki MX Ports
  ansible.builtin.include_tasks: configure_ports.yml
  loop: "{{ meraki_mx_configuration.appliances }}"
  loop_control:
    loop_var: appliance

- name: Configure Threat Protection
  ansible.builtin.include_tasks: configure_threat_protection.yml
  loop: "{{ meraki_mx_configuration.appliances }}"
  loop_control:
    loop_var: appliance

- name: Configure L3 Firewall Rules
  ansible.builtin.include_tasks: configure_l3_firewall.yml
  loop: "{{ meraki_mx_configuration.appliances }}"
  loop_control:
    loop_var: appliance

- name: Configure L7 Firewall Rules
  ansible.builtin.include_tasks: configure_l7_firewall.yml
  loop: "{{ meraki_mx_configuration.appliances }}"
  loop_control:
    loop_var: appliance
