---
- name: Query Device Serial Number for {{ ap.name }}
  cisco.meraki.meraki_device:
    auth_key: "{{ auth_key }}"
    org_name: "{{ ap.organization }}"
    net_name: "{{ ap.network }}"
    hostname: "{{ ap.name }}"
    state: query
  register: device_results

- name: Assign RF Profile for {{ ap.name }}
  cisco.meraki.meraki_mr_radio:
    auth_key: "{{ auth_key }}"
    org_name: "{{ ap.organization }}"
    net_name: "{{ ap.network }}"
    serial: "{{ device_results['data'][0]['serial'] }}"
    state: present
    rf_profile_id: "{{ rf_profile_ids[ap.rf_profile_name].rf_profile_id }}"
