---
- name: Configuring General Wireless Settings for {{ ap.network }}
  cisco.meraki.meraki_mr_settings:
    auth_key: "{{ auth_key }}"
    org_name: "{{ ap.organization }}"
    net_name: "{{ ap.network }}"
    state: present
    ipv6_bridge_enabled: "{{ ap.general_settings.ipv6_bridge_enabled | default(omit) }}"
    led_lights_on: "{{ ap.general_settings.led_lights_on | default(omit) }}"
    location_analytics_enabled: "{{ ap.general_settings.location_analytics_enabled | default(omit) }}"
    meshing_enabled: "{{ ap.general_settings.meshing_enabled | default(omit) }}"
    upgrade_strategy: "{{ ap.general_settings.upgrade_strategy | default(omit) }}"
  when: ap.general_settings is defined
