---
- name: Configuring Wireless SSIDs
  cisco.meraki.networks_wireless_ssids:
    meraki_api_key: "{{ auth_key }}"
    networkId: "{{ network_id }}"
    name: "{{ ssid.name }}"
    number: "{{ ssid.number }}"
    state: "{{ ssid.state }}"
    enabled: "{{ ssid.enabled }}"
    visible: "{{ ssid.visible | default(omit) }}"
    availableOnAllAps: "{{ ssid.availableOnAllAps | default(omit) }}"
    authMode: "{{ ssid.authentication.authMode | default(omit) }}"
    psk: "{{ ssid.authentication.psk | default(omit) }}"
    encryptionMode: "{{ ssid.authentication.encryptionMode | default(omit) }}"
    wpaEncryptionMode: "{{ ssid.authentication.wpaEncryptionMode | default(omit) }}"
    useVlanTagging: "{{ ssid.vlan.useVlanTagging | default(omit) }}"
    defaultVlanId: "{{ ssid.vlan.defaultVlanId | default(omit) }}"
    ipAssignmentMode: "{{ ssid.ipAssignmentMode | default(omit) }}"
    lanIsolationEnabled: "{{ ssid.lanIsolationEnabled | default(omit) }}"
    splashPage: "{{ ssid.splashPage | default(omit) }}"
  loop: "{{ ap.ssids }}"
  loop_control:
    loop_var: ssid
  when: ssid.state == "present"
