---
#
# Ansible Role to Configure Meraki MR Access Points
#
# Copyright (C) 2023 World Wide Technology
# All Rights Reserved
#
# Written by: Nick Thompson (github/@nsthompson)
#
- name: Look Up Meraki MR Access Point Network ID
  ansible.builtin.set_fact:
    network_id: "{{ lookup('wwt.meraki.fetch', 'network_id', org_name=meraki_mr_configuration.network.organization, meraki_api_key=auth_key, network_name=meraki_mr_configuration.network.name) }}"

- name: Remove Default SSID
  ansible.builtin.include_tasks: remove_default_ssid.yml
  loop: "{{ meraki_mr_configuration.access_points }}"
  loop_control:
    loop_var: ap
  tags:
    - wireless
    - ssid

- name: Configure General Settings
  ansible.builtin.include_tasks: configure_general_settings.yml
  loop: "{{ meraki_mr_configuration.access_points }}"
  loop_control:
    loop_var: ap
  tags:
    - wireless

- name: Configure RF Profiles
  ansible.builtin.include_tasks: configure_rf_profiles.yml
  loop: "{{ meraki_mr_configuration.access_points }}"
  loop_control:
    loop_var: ap
  tags:
    - wireless
    - rf_profiles

- name: Assign RF Profiles
  ansible.builtin.include_tasks: assign_rf_profiles.yml
  loop: "{{ meraki_mr_configuration.access_points }}"
  loop_control:
    loop_var: ap
  tags:
    - wireless
    - rf_profiles

- name: Configure SSIDs
  ansible.builtin.include_tasks: configure_ssids.yml
  loop: "{{ meraki_mr_configuration.access_points }}"
  loop_control:
    loop_var: ap
  tags:
    - wireless
    - ssid

- name: Remove SSIDs
  ansible.builtin.include_tasks: remove_ssids.yml
  loop: "{{ meraki_mr_configuration.access_points }}"
  loop_control:
    loop_var: ap
  tags:
    - wireless
    - ssid

- name: Configure Bluetooth Settings
  ansible.builtin.include_tasks: configure_bluetooth.yml
  loop: "{{ meraki_mr_configuration.access_points }}"
  loop_control:
    loop_var: ap
  tags:
    - wireless
    - bluetooth
