---
#
# Ansible Role to Configure Meraki MR Access Points
#
# Copyright (C) 2023 World Wide Technology
# All Rights Reserved
#
# Written by: Nick Thompson (github/@nsthompson)
#
- name: Get Meraki Network IDs
  cisco.meraki.meraki_network:
    auth_key: "{{ auth_key }}"
    org_name: "{{ ap.organization }}"
    net_name: "{{ ap.network }}"
    state: query
  loop: "{{ meraki_mr_configuration.access_points }}"
  loop_control:
    loop_var: ap
  register: network_results

- name: Failure - Network DOES NOT exist
  ansible.builtin.fail:
    msg: Meraki Network is not provisioned
  when: network_results.results[0].data.id is not defined

- name: Build dict of Network Name to IDs
  ansible.builtin.set_fact:
    network_ids: >-
      {{ network_ids | default({}) | combine(
        {
          result.data.name: {
            "network_id": result.data.id,
          }
        }
      ) }}
  loop: "{{ network_results.results }}"
  loop_control:
    loop_var: result

- name: Remove Default SSID
  ansible.builtin.include_tasks: remove_default_ssid.yml
  loop: "{{ meraki_mr_configuration.access_points }}"
  loop_control:
    loop_var: ap
  tags:
    - wireless
    - ssid

- name: Configure General Settings
  ansible.builtin.include_tasks: configure_general_settings.yml
  loop: "{{ meraki_mr_configuration.access_points }}"
  loop_control:
    loop_var: ap
  tags:
    - wireless

- name: Configure RF Profiles
  ansible.builtin.include_tasks: configure_rf_profiles.yml
  loop: "{{ meraki_mr_configuration.access_points }}"
  loop_control:
    loop_var: ap
  tags:
    - wireless
    - rf_profiles

- name: Assign RF Profiles
  ansible.builtin.include_tasks: assign_rf_profiles.yml
  loop: "{{ meraki_mr_configuration.access_points }}"
  loop_control:
    loop_var: ap
  tags:
    - wireless
    - rf_profiles

- name: Configure SSIDs
  ansible.builtin.include_tasks: configure_ssids.yml
  loop: "{{ meraki_mr_configuration.access_points }}"
  loop_control:
    loop_var: ap
  tags:
    - wireless
    - ssid

- name: Configure Bluetooth Settings
  ansible.builtin.include_tasks: configure_bluetooth.yml
  vars:
    network_id: "{{ network_ids[ap.network]['network_id'] }}"
  loop: "{{ meraki_mr_configuration.access_points }}"
  loop_control:
    loop_var: ap
  tags:
    - wireless
    - bluetooth
