---
- name: Set default_ssid to {{ meraki_mr_configuration.network.name + ' - wireless WiFi' }}
  ansible.builtin.set_fact:
    default_ssid: "{{ meraki_mr_configuration.network.name + ' - wireless WiFi' }}"

- name: Check for Existing SSIDs
  cisco.meraki.networks_wireless_ssids_info:
    meraki_api_key: "{{ auth_key }}"
    networkId: "{{ network_id }}"
  register: ssid_results

- name: Parse SSID Data
  ansible.builtin.set_fact:
    ssid_data: >-
      {{ ssid_data | default({}) | combine(
        {
          response.name: {
            "number": response.number,
            "enabled": response.enabled
          }
        }
      ) }}
  loop: "{{ ssid_results.meraki_response }}"
  loop_control:
    loop_var: response
  when: ssid_results.meraki_response is defined

- name: Remove and Disable Default SSID
  cisco.meraki.networks_wireless_ssids:
    meraki_api_key: "{{ auth_key }}"
    state: present
    name: "{{ 'Unconfigured SSID ' + ((ssid_data[default_ssid].number | int + 1) | string) }}"
    number: "{{ ssid_data[default_ssid]['number'] }}"
    enabled: false
    networkId: "{{ network_id }}"
  when: ssid_data[default_ssid] is defined and ssid_data[default_ssid]['enabled'] is true
