---
argument_specs:
  # roles/configure_meraki_mx/main.yml entry point
  main:
    short_description: Role to configure Meraki MX Appliances
    author: Nick Thompson <github/@nsthompson>
    options:
      auth_key:
        type: str
        required: true
        description: Meraki API Auth Key
      meraki_mx_configuration:
        type: dict
        required: true
        options:
          appliances:
            type: list
            required: true
            description: Meraki MX Appliances being Configured
            elements: dict
            options:
              name:
                type: str
                required: true
                description: Name of MX Appliance
              organization:
                type: str
                required: true
                description: Meraki Organization
              network:
                type: str
                required: true
                description: Meraki Network Name
              deployment_settings:
                type: dict
                required: true
                options:
                  deployment_mode:
                    type: str
                    required: true
                    description: Appliance Deployment Mode
                    choices:
                      - routed
                      - passthrough
                  client_tracking:
                    type: str
                    required: true
                    description: Meraki Client Tracking Method
                    choices:
                      - MAC address
                      - IP address
                      - Unique client identifier
                  dynamic_dns:
                    type: dict
                    required: true
                    options:
                      prefix:
                        type: str
                        required: false
                        description: Dynamic DNS Prefix
                      enabled:
                        type: bool
                        required: false
                        description: Dynamic DNS enabled
              lan_settings:
                type: dict
                required: true
                options:
                  enable_vlans:
                    type: bool
                    required: true
                    description: Enable VLAN Mode
              vlans:
                type: list
                required: true
                elements: dict
                options:
                  id:
                    type: int
                    required: true
                    description: VLAN ID
                  state:
                    type: str
                    required: true
                    description: VLAN State
                    choices:
                      - present
                      - absent
                  name:
                    type: str
                    required: false
                    description: VLAN Name
                  subnet:
                    type: str
                    required: false
                    description: Subnet for VLAN
                  appliance_ip:
                    type: str
                    required: false
                    description: Default Gateway on MX
                  reserved_ip_range:
                    type: list
                    required: false
                    elements: dict
                    options:
                      start:
                        type: str
                        required: false
                        description: Starting IP address
                      end:
                        type: str
                        required: false
                        description: End IP Address
                      comment:
                        type: str
                        required: false
                        description: DHCP Comment
                  fixed_ip_assignments:
                    type: list
                    required: false
                    elements: dict
                    options:
                      mac:
                        type: str
                        required: false
                        description: Client MAC Address
                      ip:
                        type: str
                        required: false
                        description: Client IP Address
                      name:
                        type: str
                        required: false
                        description: Client Name
                  dns_nameservers:
                    type: str
                    required: false
                    description: Semi-colon delimited list of DNS IP addresses or opendns, google_dns, upstream_dns
              ports:
                type: list
                required: true
                elements: dict
                options:
                  id:
                    type: int
                    required: true
                    description: Port ID
                  enabled:
                    type: bool
                    required: true
                  drop_untagged_traffic:
                    type: bool
                    required: false
                    description: Drop Untagged Traffic - Can only be set if port type is trunk
                  type:
                    type: str
                    required: false
                    description: Port Type
                    choices:
                      - access
                      - trunk
                  vlan:
                    type: int
                    required: false
                    description: Access VLAN or Trunk Native VLAN
                  allowed_vlans:
                    type: str
                    required: false
                    description: Comma-separated list of VLAN IDs or all
                  access_policy:
                    type: str
                    required: false
                    description: Port Access Policy
                    choices:
                      - open
                      - 8021x-radius
                      - mac-radius
                      - hybrid-radius
