---
name: "Release collection on Galaxy"
on:
  release:
    types: [published]

jobs:
  release_ansible_galaxy:
    uses: ansible/ansible-content-actions/.github/workflows/release_galaxy.yaml@main
    with:
      environment: release
    secrets:
      ansible_galaxy_api_key: ${{ secrets.ANSIBLE_GALAXY_API_KEY }}
